### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by arcanewater** [toniperic/php-clash-of-clans#2]
Does this still work? Since offical api now requires API key? So will this lib be updated?

**Comment by toniperic** [comment]
Yeah this should still work, but since there is an official API I will be updating this package to reflect the changes. Can't say the exact date but it will be updated soon.

**Comment by arcanewater** [comment]
Great! Looking forward to it !

**Comment by toniperic** [comment]
Just updated, feel free to explore the API and make more suggestions!

Gonna close this one now, thanks!
